dbt_unit_test:
  target: test
  outputs:
    test:
      dataset: dbt_unit_test
      fixed_retries: 1
      keyfile: your-service-account-path.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: data-bootcamp-skooldio
      threads: 1
      timeout_seconds: 300
      type: bigquery